(define (aplicar campos)
  (let ((valor (hash-try-get campos "geo_confianza")))
    (if (not valor)
      (hash-insert campos "geo_confianza" "ausente")
      (hash-insert campos "geo_confianza" valor))))